### ISSUE TITLE
Include Simple Form for form generation

### ISSUE THREAD

**Issue by LukasPol** [LukasPol/rails-template#5]
Simple Form is a convenient tool for generating forms in Rails applications. 

This issue focuses on including Simple Form in the template to streamline the process of creating and customizing forms.

**Tasks:**
- [ ] Add Simple Form to the Gemfile.
- [ ] Configure Simple Form for use in the template.
- [ ] Update documentation to provide guidance on using Simple Form for form generation.
